### ISSUE TITLE
Fehlt Funktion 'Alle Treffer dieser Seite auf eine Merkliste'

### ISSUE THREAD

**Issue by mschwendener** [swissbib/sbvf2#124]
Unter TouchPoint haben wir die Möglichkeit, alle Treffer, die auf einer Seite angezeigt werden, gleichzeitig auf einer Merkliste zu speichern. Die Funktion fehlt noch.

Anstatt sie nachzubauen, würde ich aber vorschlagen, die Darstellung aus http://devbabe.swissbib.ch/MyResearch/Lists zu übernehmen, also das 'Auf die Merkliste'-Icon durch Auswahlkästchen zu ersetzen und die Funktion 'Alle auswählen' anzubieten, plus 'Auf Merkliste speichern'.

Würde der originalen VuFind-Oberfläche http://vufind.org/demo entsprechen und man hätte die Wahl, alle Treffer einer Seite auf der Merkliste zu speichern oder einzelne (aber mehrere) auszuwählen.

**Comment by oschihin** [comment]
Ist mit swissbib/vufind#359 in Diskussion
