### ISSUE TITLE
Vernacular aktivieren oder eigene Lösung aufbauen

### ISSUE THREAD

**Issue by ToVie** [swissbib/sbvf2#314]
Die Anzeige der Vernacular-Elemente aus den Feldern 880  angepasst mindestens für Hebräisch, Arabisch, Kyrillisch, CJK

Beispiele
-------------
* Kyrillisch: https://test.swissbib.ch/Record/244633207
* Arabisch: https://test.swissbib.ch/Record/234679050
* Hebräisch: https://test.swissbib.ch/Record/122061233
* Chinesisch: https://test.swissbib.ch/Record/194946762
* Koreanisch: https://test.swissbib.ch/Record/197741223
* Japanisch: https://test.swissbib.ch/Record/133220141

Dokumentation & Info
-------------------------------
Offenbar wenig.
* alte Diskussion (2008) http://sourceforge.net/mailarchive/forum.php?thread_name=c162d5540803282044pfdc01a0ocddfd95f35bdb668%40mail.gmail.com&forum_name=vufind-general
* Offene Tickets?

**Comment by oschihin** [comment]
ist übernommen
