### ISSUE TITLE
'Erweiterte Suche - Suche verfeinern' wird nicht als erweiterte Suche behandelt

### ISSUE THREAD

**Issue by mschwendener** [swissbib/sbvf2#459]
'Erweiterte Suche - Suche verfeinern' setzt eine einfache Suche ab, keine erweiterte.

Erkennbar daran, dass der Balken (https://github.com/swissbib/sbvf2/issues/110), der nach einer erweiterten Suche erscheint, nicht angezeigt wird.  

Richtig wäre https://github.com/swissbib/sbvf2/issues/430: Suche verfeinern müsste in jeder Suchgruppe vorkommen.

**Comment by chantalw** [comment]
@witzigs: Ich verstehe zwar nicht ganz, was da gemeint war, aber ich denke, diesen Issue kann man schliessen - oder?

**Comment by mschwendener** [comment]
Schliessen ok. Ist zwar immer noch so, aber ich glaube die Darstellung ist besser als vorher.

Gemeint war: ich klicke auf 'Erweiterte Suche', wähle dort **nur im unteren Teil** ('Suche verfeinern') ein Kriterium oder mehrere -> die Trefferliste hat im orangen Titelbalken nicht die Optionen 
"Erweiterte Suche bearbeiten / Neue erweiterte Suche starten / Neue einfache Suche starten".

**Comment by chantalw** [comment]
@mschwendener: Aha, jetzt versteh ichs, danke. Lasse den Issue aber jetzt mal geschlossen, ist vermutlich nicht allzu häufig, dass jemand diese Suchmöglichkeit (nur "Suche verfeinern") verwendet. Gewählte Kriterien abwählen kann man ja, auch (thematische) Suchbegriffe varieren mit der Option "Behalte die Filtereinstellungen". Eine Sprache, Format oder Bibliothek mit OR-Kombination hinzufügen geht nicht, aber das kommt hoffentlich dann auch noch...
