### ISSUE TITLE
505-Code in SolrMarc.php wirft bei Satz "https://test.swissbib.ch/Record/306368218" eine exception

### ISSUE THREAD

**Issue by ToVie** [swissbib/sbvf2#500]
505-Code in SolrMarc.php wirft bei Satz "https://test.swissbib.ch/Record/306368218" eine exception

Problembeschreibung
----
Der Grund liegt darin, dass der der diesem Record zugrundeliegende RERO-Satz ein 505-Feld enthält, das mit $g eingeleitet wird aber kein $t oder $r enthält, wie eigentlich vorgeschrieben und von der Routine erwartet.

(Die drei nachfolgenden 505-Felder liefern den Grund. Bei "$g" handelt es sich um einen Vertipper, es müsste "$a" gesetzt werden.)

```
505	0	- 	$g DVD 1 : Werner Stauffacher. - 52 Min.
505	0	-	$a DVD 2 : Hans Waldmann & Niklaus von Flüe. - 51 Min.
505	0	-	$a DVD 3 : Guillaume Henri Dufour. - 52 Min.
505	0	-	$a DVD 4 : Alfred Escher & Stefano Franscini. - 52 Min. 
```
(RERO-Nr: R007563932) - http://opac.rero.ch/gateway?beginsrch=1&lng=de&inst=consortium&search=KEYWORD&function=CARDSCR&t1=R007563932&u1=12

Lösung
---
den Mechanismus fehlertoleranter machen, da dies immer mal wieder vorkommen kann....

**Comment by oschihin** [comment]
@ToVie kann ich nicht mehr nachvollziehen, der Satz wurde offenbar korrigiert
