### ISSUE TITLE
Bessere Steuerung der URL-Anzeige in swissbib

### ISSUE THREAD

**Issue by ToVie** [swissbib/sbvf2#507]
Problem
----
swissbib zeigt aufgrund der Zusammenführung von Dokumenten aktuell in vielen Fällen redundante URLs an. Dies betrifft hauptsächlich Inhaltsverzeichnisse und Abstracts. Diese Situation ist für die NutzerInnen unübersichtlich und von der Darstellung her sinnlos.

Analyse
----
Links kommen in jedem Fall aus zwei Feldern:
- 950/856
- 956

Dies betrifft jegliche Form von Links also auch solche auf Inhaltsverzeichnisse. Versucht man nun Inhaltsverzeichnisse von URLs zu trennen, muss man einerseits Selektionskriterien für die Inhaltsverzeichnisse definieren und andererseits Ausschlusskriterien für die generelle Linkanzeige erstellen.

Lösung
----
Schaffe eine konfigurierbare Routine zur Selektion von URLs, die es erlaubt, Links anhand spezifischer Kriterien auszuwählen oder auszuschliessen.

**Beispiele für Selektionskriterien Inhaltsverzeichnisse**
**Feld 950**
$P 856 && $3 Inhalt*
$P 856 && $z Inhalt*
$P 856 && $u ^http.*d-nb.*04$
$P 856 && $u ^http.*loc.gov.*toc.*
$P 856 && $u ^http.*.admin.ch.*\/toc\/pdf\/.*
$P 856 && $u ^http.*deposit.d-nb.*" && $z .*text$

**Feld 956**
$y Inhaltsverzeichnis
$y Abstract
$u ^http.*d-nb.*04$

Umgekehrt werden für den Standard-Link die Selektionskriterien für Inhaltsverzeichnisse als Ausschlusskriterien verwendet. Dazu kommen noch folgende Ausschlusskriterien:

**Feld 856**
$u helveticarchives

**Feld 956**
$x VIEW && $y Porträt

Beispielsätze zur Analyse
----
**URLs von Inhaltsverzeichnissen**
https://test.swissbib.ch/Record/27166116X
https://test.swissbib.ch/Record/126069557
https://test.swissbib.ch/Record/304555274
https://test.swissbib.ch/Record/281298521
https://test.swissbib.ch/Record/268600961
https://test.swissbib.ch/Record/071086048

**Ausschlusskriterien**
__$x VIEW && $y Porträt__
https://test.swissbib.ch/Record/088908437
https://test.swissbib.ch/Record/093806418

**Comment by oschihin** [comment]
übernommen in neues Repo
