### ISSUE TITLE
Ausleihen ohne Verlängerungsmöglichkeit

### ISSUE THREAD

**Issue by oschihin** [swissbib/sbvf2#521]
Problem
-----------
Im Konto > Ausleihen ist angegeben, ob ein Titel verlängerbar ist oder nicht (Checkbox und Text). Es ist jedoch nicht ersichtlich, ob die Verlängerung nicht erlaubt ist wegen eines Rückrufs oder weil die Höchstzahl Verlängerungen (5 von 5) erreicht ist.

Ziel
-----
Es muss ersichtlich sein, dass ein Titel die maximale Anzahl Verlängerungen erreicht hat, oder dass ein Rückruf drauf liegt.

**Comment by oschihin** [comment]
@witzigs : ev. übernehmen und schliessen

**Comment by witzigs** [comment]
Über REST ist nur sichtbar, ob eine Ausleihe verlängerbar ist oder nicht sowie die Anzahl der bereits erfolgten Verlängerungen. Ob ein Rückruf oder ein anderer Grund (Sperre) vorliegt, ist nicht ersichtlich. Ich schliesse daher hier.
