### ISSUE TITLE
Bibliotheksinfos verlinken in Ansicht "Ausleihen"

### ISSUE THREAD

**Issue by chantalw** [swissbib/sbvf2#549]
Im Fenster Ausleihe, Spalte "Bibliothek" die Bibliotheksinfos verlinken. Falls nicht möglich, dann auf dieser Ebene einen Link einfügen auf http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/ 
Wenn möglich, könnte man die Verlinkung auch gleich in der Ansicht "Reservationen" vornehmen.

**Comment by oschihin** [comment]
@witzigs : Falls der Wunsch neu wieder aufgetaucht ist, hier schliessen. Sonst ev. Issue übernehmen.
