### ISSUE TITLE
Verzerrte Trefferliste nach erweiterter Suche

### ISSUE THREAD

**Issue by chantalw** [swissbib/sbvf2#558]
Nach einer Suche "malaria vaccine tanner" (erweiterte Suche in allen Feldern wie auch einfache Suche) bekam ich vorhin eine verzerrte, zu breite Trefferliste:
![trefferliste-verzerrt_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5437080/844bfc92-846d-11e4-889d-696189167117.jpg)

**Comment by chantalw** [comment]
@oschihin @witzigs Interessanterweise passiert das bei genau dieser Suchanfrage auch im neuen Design! Allerdings nur auf dem grossen Desktop-Bildschirm und nur Tab 1 (vgl. Screenshot), iPhone und Tab 2 scheinen ok. 
Stört mich ja nicht wirklich, und es scheint aus irgend einem Grund nur bei diesen Suchbegriffen vorzukommen... Eröffne den Issue nicht wieder neu, wollte es euch aber einfach zur Kenntnis bringen...
![verzerrte-trefferliste_2015-05-11](https://cloud.githubusercontent.com/assets/5259782/7561632/ec45d95c-f7cd-11e4-975c-342d903d6cf7.jpg)

**Comment by oschihin** [comment]
@chantalw 
siehe swissbib/vufind#108 sollte nächstens gefixt werden.
