### ISSUE TITLE
Navigation bei Bestellung/Vormerkung eines Titels

### ISSUE THREAD

**Issue by chantalw** [swissbib/sbvf2#60]
Wenn man aus einer Treffer- oder Merkliste heraus einen Titel bestellt/vormerkt, kommt man aus der Ansicht "offene Bestellungen" nicht mehr zurück zur Treffer-/Merkliste. Direktlink zurück scheint mir notwendig.

**Comment by oschihin** [comment]
@chantalw : wie steht es damit in der neuen Oberfläche? Ev. Issue übernehmen und hier schliessen

**Comment by chantalw** [comment]
@oschihin @witzigs Das scheint mir jetzt erfüllt, ich schliesse den Issue.
